name       : dfarc
version    : 3.14
release    : 2
source     :
    - https://ftp.gnu.org/gnu/freedink/dfarc-3.14.tar.gz : a51124ecd11eeca0f1d16732ef58ee690e2fa2db06cc0ec2a5b61b41f8b0e8fa
license    : GPL-3.0-or-later
component  : games.rpg
summary    : Dink front-end and archiver, which helps running and managing D-Mods
description: |
    DFArc is the Dink front-end and archiver, which helps running and managing D-Mods.
builddeps  :
    - bzip2-devel
    - wxwidgets-devel
rundeps    :
    - freedink
    - xdg-utils
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
